server:
  port: 0

spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/generic-project-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans

